# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GuiltHub
email: chrisdcastle [at] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal website for Chris Castle
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://89million.github.io" # the base hostname & protocol for your site
twitter_username: computersdotcom
github_username:  89million

# Build settings
markdown: kramdown
